development = false
snowFlakeId = 1
etcd = ["ip:port"]
[mysql]
addr = "ip:port"
user = "user"
password = "password"
dbName = "only-id"
maxConn = 20
idleConn = 10
idleTimeout = 14400000
queryTimeout = 800
execTimeout = 800
[log]
logFileDir = "logs"
appName = "OnlyID"
maxSize = 100
maxBackups = 60
maxAge = 30
level  = "debug"
[server]
addr= "127.0.0.1:8082"